config/routes.rb
Rails.application.routes.draw do

  devise_for :users

    #nesting urls

    resources :projects do
       resources :subjects, module: :projects
   end

end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :user

  has_many :statuses

  accepts_nested_attributes_for :statuses

  validates :title, presence: true

validates_associated :statuses

end

app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :user

  belongs_to :project

  #The line below makes it so a description is required,
  #not sure how you want yours to be so I just wanted to point it out for you.
  #validates :description, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects

  has_many :statuses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects/statuses_controller.rb
class Statuses::ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project

  def create
    @status = @project.status.new status_params
    @status.user = current_user.id

    if @status.save
      
      redirect_to project_path(@project, anchor: "status_#{@status.id}"), notice: "Successfully posted!"
    else
      redirect_to @project, alert: "Unable to save your status"
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def status_params
      params.require(:status).permit(:description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, except: [:index, :new, :create]

  def index
    @projects = Project.all
  end

  def show
    @status = Status.new
  end

  def new
    @project = Project.new
    @project.statuses.new

  end

  def create
    @project = current_user.projects.new project_params

    if @project.save
      redirect_to @project
    else
      render action: :new
    end
  end

  private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
        params.require(:project).permit(:title, :description, :startdate, statuses_attributes: [:description])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P3prototype</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div>
	  <%= f.label "Start date" %><br>
	    <%= f.date_field :startdate %>
  </div>

<div>
  <%= f.fields_for :statuses do |p| %>
  <div class="form-group">
    <%= p.text_area :description, placeholder: "Describe your new status", rows: 10, class: "form-control" %>
  </div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div id = "wrapper">
<div align=center>
<h1>WHAT IS [USER] WORKING ON RIGHT NOW?</h1>
<h3>get in touch at user@email.com</h3>
</div>

<% @projects.each do |project|%>
	<div class="project">
		<p><%= project.title %></p>
		<p>since <%= project.startdate %></p>
		<div class="status">
      <h1>Project Status Updates:</h1>
      <%= render 'statuses/status' %>
		</div>
	</div>
<% end %>
</div>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Picture</th>
	  <th>Description</th>
	  <th>Start date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
		<td><%= project.startdate %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form" %>

app/views/projects/show.html.erb
<div class="container">
    <h1><%= @project.title %></h1>
  <p class="text-muted">Created by <%= @project.user.email %>
  </p>
  <%= render @project.statuses %>

  <hr />
  <%= render partial: "statuses/form" %>
</div>

app/views/statuses/_form.html.erb
<%= form_for [@project, @status] do |f| %>

  <div class="form-group">
    <%= f.text_area :description, placeholder: "New status here", rows: 10, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div class="row">
      <div class="col-md-6">
     <div class="panel panel-default">
      <div class="panel-heading">
          <h1>Status</h1>
     </div>
     <div class='panel-body'>
             <% current_user.statuses.each do |status| %>

         <h1><%= status.description %></h1>
             <strong><p>This status was posted on <%= status.created_at.strftime("%B %e, %Y at %l:%M %p") %></p></strong>

        </div>
<% end %>

      </div>
    </div>
</div>